// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwCLxXwwJvxR3IWKbuCw2nPWg1XuQs1jA',
    appId: '1:247007993319:web:385991bc99eceb60267142',
    messagingSenderId: '247007993319',
    projectId: 'fir-tutorial-7a72b',
    authDomain: 'fir-tutorial-7a72b.firebaseapp.com',
    storageBucket: 'fir-tutorial-7a72b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnX97LyJlLmHLI1Cg6S2uJNWpEtMe_SwQ',
    appId: '1:247007993319:android:5ec3a16ac88d7474267142',
    messagingSenderId: '247007993319',
    projectId: 'fir-tutorial-7a72b',
    storageBucket: 'fir-tutorial-7a72b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH9yIPbqxj_ksQVHmso9phpvOlw-lz8LY',
    appId: '1:247007993319:ios:ed166fdc9f79b88f267142',
    messagingSenderId: '247007993319',
    projectId: 'fir-tutorial-7a72b',
    storageBucket: 'fir-tutorial-7a72b.appspot.com',
    iosClientId: '247007993319-fivlg6teafk5irhr6ea1plbmcjvsih77.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH9yIPbqxj_ksQVHmso9phpvOlw-lz8LY',
    appId: '1:247007993319:ios:ed166fdc9f79b88f267142',
    messagingSenderId: '247007993319',
    projectId: 'fir-tutorial-7a72b',
    storageBucket: 'fir-tutorial-7a72b.appspot.com',
    iosClientId: '247007993319-fivlg6teafk5irhr6ea1plbmcjvsih77.apps.googleusercontent.com',
    iosBundleId: 'com.example.loginFirebaseTest',
  );
}
